# Generated by Django 3.2.4 on 2021-06-19 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set_group', related_query_name='user_group_query', to='auth.Group', verbose_name='groups')),
                ('tag', models.ManyToManyField(blank=True, to='master.TagMaster')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set_permissions', related_query_name='user_permissions_query', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_period_started', models.BooleanField(default=False)),
                ('is_ovulation', models.BooleanField(default=False)),
                ('temperature', models.PositiveSmallIntegerField()),
                ('temperature_unit', models.CharField(max_length=5)),
                ('weight', models.PositiveSmallIntegerField()),
                ('weight_unit', models.CharField(max_length=5)),
                ('sleep_min', models.IntegerField()),
                ('mood', models.PositiveSmallIntegerField(choices=[(1, 'Good'), (2, 'Bad'), (3, 'Other')], default=1)),
                ('cervical_fluid', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10, verbose_name='period/spotting')),
                ('test_devices_Std_Opk', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Positive'), (3, 'Negative')], default=1)),
                ('Advance_Opk', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Low'), (3, 'Medium'), (4, 'High')], default=1)),
                ('pregnancy_test', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Positive'), (3, 'Negative')], default=1)),
                ('Blood', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Positive'), (3, 'Negative')], default=1)),
                ('progesterone_test', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Positive'), (3, 'Negative')], default=1)),
                ('Ferning_Microscope', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'None'), (3, 'Partial'), (4, 'Full')], default=1)),
                ('ivf', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Retrieval'), (3, 'Transfer'), (4, 'Freezing')], default=1)),
                ('Insermination', models.PositiveSmallIntegerField(choices=[(1, 'Not Available'), (2, 'Iui'), (3, 'Icsi'), (4, 'Ivi'), (5, 'Hcg'), (6, 'Hsg Exam'), (7, 'Shg Exam')], default=1)),
                ('osteoporosis', models.DateField()),
                ('heart_disease', models.DateField()),
                ('from_uninary_incontinence_diabetes', models.DateField()),
                ('to_uninary_incontinence_diabetes', models.DateField()),
                ('stroke', models.DateField()),
                ('biomaker_result', models.PositiveSmallIntegerField()),
                ('biomaker_result_unit', models.CharField(max_length=10)),
                ('biomaker_date', models.DateField()),
                ('biomaker_result_period_day', models.CharField(default=0, max_length=5)),
                ('progesterone_result', models.PositiveSmallIntegerField()),
                ('progesterone_result_unit', models.CharField(max_length=10)),
                ('progesterone_date', models.DateField()),
                ('progesterone_result_period_day', models.CharField(default=0, max_length=5)),
                ('comment', models.TextField(max_length=200)),
                ('symptoms_conditions', models.ManyToManyField(blank=True, to='master.TagMaster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
