# Generated by Django 3.2.4 on 2021-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('is_period_started', models.BooleanField(default=False)),
                ('is_ovulation', models.BooleanField(default=False)),
                ('temperature', models.PositiveSmallIntegerField()),
                ('temperature_unit', models.CharField(max_length=5)),
                ('weight', models.PositiveSmallIntegerField()),
                ('weight_unit', models.CharField(max_length=5)),
                ('sleep_min', models.IntegerField()),
                ('mood', models.PositiveSmallIntegerField(choices=[(1, 'Good'), (2, 'Bad'), (3, 'Other')], default=1)),
                ('cervical_fluid', models.CharField(max_length=10)),
                ('period_spotting', models.CharField(max_length=10, verbose_name='period/spotting')),
            ],
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='cervical_fluid',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='is_ovulation',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='is_period_started',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='period',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='sleep_min',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='temperature_unit',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='userhealth',
            name='weight_unit',
        ),
    ]
