# Generated by Django 3.2.4 on 2021-06-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userhealth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhealth',
            old_name='tem_unit',
            new_name='temperature_unit',
        ),
    ]
