# Generated by Django 3.2.4 on 2021-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMessageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.PositiveIntegerField(choices=[(1, 'Exercise')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.SmallIntegerField()),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
