# Generated by Django 3.2.4 on 2021-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210621_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingactivitymaster',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eatrainbowmaster',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meditationmaster',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sugarintakeactivitymaster',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
