# Generated by Django 3.2.4 on 2021-06-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210624_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatrainbowmaster',
            old_name='order',
            new_name='sequence',
        ),
    ]
