# Generated by Django 3.2.4 on 2021-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rename_order_eatrainbowmaster_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkingactivitymaster',
            old_name='order',
            new_name='sequence',
        ),
        migrations.RenameField(
            model_name='exercisemaster',
            old_name='ordering',
            new_name='sequence',
        ),
        migrations.RenameField(
            model_name='meditationmaster',
            old_name='order',
            new_name='sequence',
        ),
        migrations.RenameField(
            model_name='sugarintakeactivitymaster',
            old_name='order',
            new_name='sequence',
        ),
    ]
