# Generated by Django 3.2.4 on 2021-06-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Activity Title')),
            ],
        ),
        migrations.CreateModel(
            name='AddCustomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=20)),
                ('stat_date', models.DateField()),
                ('duration_in_days', models.CharField(max_length=50)),
                ('target_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkingWaterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_actual', models.BooleanField(default=False)),
                ('water', models.PositiveSmallIntegerField(default=5)),
                ('soft_drink', models.PositiveSmallIntegerField(default=0)),
                ('smoothie', models.PositiveSmallIntegerField(default=0)),
                ('ice_tea', models.PositiveSmallIntegerField(default=0)),
                ('fruit_juice', models.PositiveSmallIntegerField(default=0)),
                ('coffee', models.PositiveSmallIntegerField(default=0)),
                ('bear', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EatRainbowActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_actual', models.BooleanField(default=False)),
                ('red_serving', models.PositiveSmallIntegerField(default=0)),
                ('cream_serving', models.PositiveSmallIntegerField(default=0)),
                ('yellow_serving', models.PositiveSmallIntegerField(default=0)),
                ('kiwi_serving', models.PositiveSmallIntegerField(default=0)),
                ('blue_serving', models.PositiveSmallIntegerField(default=0)),
                ('green_serving', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EatRainbowMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('red_serving', models.PositiveSmallIntegerField(default=0)),
                ('cream_serving', models.PositiveSmallIntegerField(default=0)),
                ('yellow_serving', models.PositiveSmallIntegerField(default=0)),
                ('kiwi_serving', models.PositiveSmallIntegerField(default=0)),
                ('blue_serving', models.PositiveSmallIntegerField(default=0)),
                ('green_serving', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_actual', models.BooleanField(default=False)),
                ('duration', models.PositiveSmallIntegerField(default=90)),
                ('met', models.FloatField(default=0)),
                ('calories', models.PositiveSmallIntegerField(default=200)),
                ('feeling', models.CharField(blank=True, choices=[('GE', 'Great And Easy'), ('NR', 'Normal'), ('HR', 'Hard'), ('EX', 'Exhausted'), ('SI', 'Sick')], max_length=2, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories_burn', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Exercise Title')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exercise Category')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration_in_days', models.CharField(default=7, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SugarIntakeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_actual', models.BooleanField(default=False)),
                ('sugar_consumed', models.PositiveSmallIntegerField(default=0)),
                ('calories_gained', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('asssigned_date', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.program')),
            ],
        ),
    ]
