# Generated by Django 3.2 on 2021-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemaster',
            name='calories_burn',
        ),
        migrations.RemoveField(
            model_name='exercisemaster',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercisemaster',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exercisemaster',
            name='tag',
        ),
        migrations.AddField(
            model_name='exerciseactivity',
            name='exercise',
            field=models.ManyToManyField(blank=True, to='activity.ExerciseMaster'),
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exercise Category'),
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Exercise Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExerciseActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories_burn', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ManyToManyField(blank=True, to='activity.ExerciseMaster')),
                ('tag', models.ManyToManyField(blank=True, to='master.TagMaster')),
            ],
        ),
    ]
