# Generated by Django 3.2.4 on 2021-06-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('master', '0001_initial'),
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='eat_rainbow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.eatrainbowmaster'),
        ),
        migrations.AddField(
            model_name='program',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.exerciseactivitymaster'),
        ),
        migrations.AddField(
            model_name='program',
            name='meditation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.meditationactivity'),
        ),
        migrations.CreateModel(
            name='SugarIntakeActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_intake', models.PositiveSmallIntegerField(default=0)),
                ('calories_gained', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dessert_snack', models.ManyToManyField(blank=True, related_name='dessert_snacks', to='food.Food')),
                ('dried_fruits', models.ManyToManyField(blank=True, related_name='Dry_Fruits', to='food.Food')),
                ('drink_juices', models.ManyToManyField(blank=True, related_name='drink_juice', to='food.Food')),
                ('fruits', models.ManyToManyField(blank=True, related_name='fruits', to='food.Food')),
                ('sweet_veggie', models.ManyToManyField(blank=True, related_name='sweet_vaggies', to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkingActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveSmallIntegerField(default=5)),
                ('soft_drink', models.PositiveSmallIntegerField(default=0)),
                ('smoothie', models.PositiveSmallIntegerField(default=0)),
                ('ice_tea', models.PositiveSmallIntegerField(default=0)),
                ('fruit_juice', models.PositiveSmallIntegerField(default=0)),
                ('coffee', models.PositiveSmallIntegerField(default=0)),
                ('bear', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tag', models.ManyToManyField(blank=True, to='master.TagMaster')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='drinking_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.drinkingactivitymaster'),
        ),
        migrations.AddField(
            model_name='program',
            name='sugar_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.sugarintakeactivitymaster'),
        ),
    ]
