# Generated by Django 3.2.4 on 2021-06-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210530_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseactivitymaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
