# Generated by Django 3.2.4 on 2021-06-16 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_alter_exerciseactivitymaster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration_in_days',
            field=models.CharField(default=7, max_length=50),
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('asssigned_date', models.DateField()),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
