# Generated by Django 3.2.4 on 2021-06-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('activity', '0003_auto_20210619_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemaster',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Please enter the difficulty level for the exercise', null=True),
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='ordering',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisemaster',
            name='tag_master',
            field=models.ManyToManyField(blank=True, to='master.TagMaster'),
        ),
        migrations.AlterField(
            model_name='program',
            name='meditation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.meditationmaster'),
        ),
    ]
