# Generated by Django 3.2.4 on 2021-06-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20210616_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.program'),
        ),
    ]
