# Generated by Django 3.2.4 on 2021-06-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_userplan_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=20)),
                ('stat_date', models.DateField()),
                ('duration_in_days', models.CharField(max_length=50)),
                ('target_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitymaster')),
            ],
        ),
    ]
