# Generated by Django 3.2.4 on 2021-06-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210621_1445'),
        ('activity', '0005_auto_20210621_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.program'),
        ),
    ]
