# Generated by Django 3.2.4 on 2021-06-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210624_1732'),
        ('activity', '0007_eatrainbowactivity_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwateractivity',
            name='previous_date_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.drinkingactivitymaster'),
        ),
        migrations.AddField(
            model_name='eatrainbowactivity',
            name='previous_date_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.eatrainbowmaster'),
        ),
        migrations.AddField(
            model_name='exerciseactivity',
            name='previous_date_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.exerciseactivitymaster'),
        ),
        migrations.AddField(
            model_name='meditationactivity',
            name='previous_date_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.meditationmaster'),
        ),
        migrations.AddField(
            model_name='sugarintakeactivity',
            name='previous_date_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.sugarintakeactivitymaster'),
        ),
    ]
