# Generated by Django 3.2.4 on 2021-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_rename_previous_date_data_eatrainbowactivity_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkingwateractivity',
            old_name='previous_date_data',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='exerciseactivity',
            old_name='previous_date_data',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='meditationactivity',
            old_name='previous_date_data',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='sugarintakeactivity',
            old_name='previous_date_data',
            new_name='master',
        ),
    ]
