# Generated by Django 3.2.4 on 2021-06-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menstruation_days', models.PositiveSmallIntegerField(default=5)),
                ('follicular_days', models.PositiveSmallIntegerField(default=5)),
                ('proliferative_days', models.PositiveSmallIntegerField(default=5)),
                ('luteal_days', models.PositiveSmallIntegerField(default=5)),
                ('secretory_days', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harmones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=10)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('number_lesson', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('biology', models.TextField()),
                ('how_to_measure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=10)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('no_lesson', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('biology', models.TextField()),
                ('how_to_measure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WellnessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_menstruation', models.BooleanField(default=False)),
                ('is_follicular', models.BooleanField(default=False)),
                ('is_ovulation', models.BooleanField(default=False)),
                ('is_luteal', models.BooleanField(default=False)),
                ('is_pre_menstruation', models.BooleanField(default=False)),
                ('is_actual', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('feeling', models.ManyToManyField(blank=True, to='health.WellnessArea')),
                ('tag', models.ManyToManyField(blank=True, to='master.TagMaster')),
            ],
        ),
    ]
