# Generated by Django 3.2 on 2021-05-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_menstruation', models.BooleanField(default=False)),
                ('is_follicular', models.BooleanField(default=False)),
                ('is_ovulation', models.BooleanField(default=False)),
                ('is_luteal', models.BooleanField(default=False)),
                ('is_pre_menstruation', models.BooleanField(default=False)),
                ('is_actual', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('feeling', models.ManyToManyField(blank=True, to='health.WellnessArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AverageCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menstruation_days', models.PositiveSmallIntegerField(default=5)),
                ('follicular_days', models.PositiveSmallIntegerField(default=5)),
                ('proliferative_days', models.PositiveSmallIntegerField(default=5)),
                ('luteal_days', models.PositiveSmallIntegerField(default=5)),
                ('secretory_days', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
