# Generated by Django 3.2.4 on 2021-06-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_monthcycle_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=10)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('no_lesson', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('biology', models.TextField()),
                ('how_to_measure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=10)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('no_lesson', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('biology', models.TextField()),
                ('how_to_measure', models.TextField()),
            ],
        ),
    ]
