# Generated by Django 3.2.4 on 2021-06-19 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_medication', models.BooleanField(default=False)),
                ('doctors_name', models.CharField(max_length=20)),
                ('prescrption', models.FileField(blank=True, null=True, upload_to='')),
                ('had_surgery', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('heart_issues', models.BooleanField(default=False)),
                ('mental_issue', models.BooleanField(default=False)),
                ('additonal_info', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
