# Generated by Django 3.2.4 on 2021-06-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_healthmodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Harmones',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
