# Generated by Django 3.2.4 on 2021-06-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_harmones_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harmones',
            old_name='no_lesson',
            new_name='number_lesson',
        ),
    ]
