# Generated by Django 3.2.4 on 2021-06-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20210621_1445'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='alias_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientAlias',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
